# Generated by Django 3.0.6 on 2020-05-22 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import feed.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=100, validators=[feed.models.url_validation]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("last_fetch", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("terminated", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                ("published", models.DateTimeField()),
                ("author", models.CharField(blank=True, max_length=50)),
                ("feed", models.ManyToManyField(related_name="items", to="feed.Feed")),
                (
                    "is_favorite",
                    models.ManyToManyField(
                        related_name="favorite_items", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "is_read",
                    models.ManyToManyField(
                        related_name="read_items", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="feed_items", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"ordering": ["-published"],},
        ),
    ]
