# Generated by Django 3.0.6 on 2020-05-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_feeditem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feeditem", options={"ordering": ["-published", "is_favorite"]},
        ),
    ]
