# Generated by Django 3.0.6 on 2020-05-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_auto_20200521_1140"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feeditem", options={"ordering": ["-published"]},
        ),
    ]
